version: '3'

services: 
    postgres:
        image:
            postgres
        environment: 
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=db
        ports: 
            - "5432:5432"